In [2]:
#!pip install numpy

In [1]:
import numpy as np

In [9]:
a=np.array([])
b=np.array([1,2,3,45,0])
c=np.array([[12,3,4],[4,5,6]])

In [4]:
a

array([], dtype=float64)

In [5]:
type(a)

numpy.ndarray

In [6]:
b

array([ 1,  2,  3, 45,  0])

In [7]:
type(b)

numpy.ndarray

In [10]:
c

array([[12,  3,  4],
       [ 4,  5,  6]])

In [11]:
type(c)

numpy.ndarray

In [12]:
a.ndim

1

In [13]:
a.size

0

In [14]:
a.shape

(0,)

In [15]:
b

array([ 1,  2,  3, 45,  0])

In [16]:
b.ndim

1

In [17]:
type(b)

numpy.ndarray

In [19]:
b.size

5

In [20]:
b.shape

(5,)

In [21]:
c

array([[12,  3,  4],
       [ 4,  5,  6]])

In [22]:
c.ndim

2