In [6]:
import numpy as np

In [2]:
n=np.array([[1,2,3,4],[11,22,33,40],[5,7,9,90]])

In [3]:
n

array([[ 1,  2,  3,  4],
       [11, 22, 33, 40],
       [ 5,  7,  9, 90]])

In [4]:
n[0,1:3]

array([2, 3])

In [5]:
n[1:3,2:4]

array([[33, 40],
       [ 9, 90]])

In [6]:
n[1:,2:]

array([[33, 40],
       [ 9, 90]])

In [8]:
n[0:3,3:]

array([[ 4],
       [40],
       [90]])

# arange

In [14]:
list(range(5,51))

[5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [16]:
## arange fuction is used for arranging the range number wihout making it into list

In [18]:
np.arange(5,51)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

# Reshape

In [3]:
import numpy as np

In [4]:
a=np.arange(12).reshape(3,4)

In [26]:
# reshape is used to shape the array by adjusting no. of rows and column

In [30]:
np.sqrt(81)

9.0

In [27]:
a.max()

11

In [28]:
a.min()

0

In [31]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
a.argmax()

11

In [36]:
a*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [37]:
a+10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

# random

In [38]:
np.random.rand(2,2)

array([[0.69685388, 0.10363646],
       [0.90633652, 0.50350053]])

In [39]:
np.random.rand(2)

array([0.16050045, 0.54427641])

In [41]:
np.random.randn(2,2)

array([[ 0.84075126, -0.24579599],
       [-0.98120309,  0.59539062]])

In [42]:
np.random.randint(9,90,12)

array([16, 64, 22, 18, 49, 53, 77, 89, 49, 73, 70, 37])

In [46]:
 s=np.random.randint(9,90,12).reshape(6,2)

array([[80, 73],
       [11, 11],
       [51, 30],
       [62, 89],
       [15, 58],
       [66, 84]])

In [47]:
s

array([[73, 61],
       [50, 30],
       [58, 51],
       [34, 65],
       [47, 68],
       [29, 73]])

In [48]:
s.sum()

639

In [50]:
s.sum(axis=1)# for sum in rows

array([134,  80, 109,  99, 115, 102])

In [52]:
s.sum(axis=0) # for sum in column

array([291, 348])

# 3D array

In [7]:
d = np.array([[[4,40],[5,50],[6,60]] , [[7,70],[8,80],[9,90]] , [[5,55],[4,40],[6,60]]])

In [8]:
d.shape

(3, 3, 2)

In [9]:
(4,3,4)

(4, 3, 4)

In [61]:
# nan -not a number

In [62]:
x=np.array([12,56,np.nan,66,100,np.nan])

In [63]:
x

array([ 12.,  56.,  nan,  66., 100.,  nan])

In [64]:
x.dtype

dtype('float64')